//
//  ShowRecipeViewController.swift
//  FeedTheFridge3
//
//  Created by Micha Glissmann on 17/03/2026.
//

import UIKit


class ShowRecipeViewController: UIViewController {
    
    
    
    @IBOutlet weak var RecipeNameLabel: UILabel!
    
    @IBOutlet weak var text: UITextView!
    
    
    //function for parsing the strange JSON ingredients and JSON directions into a list of strings. (Generated by Chat GPT)
    func parseString(_ ingredientString: String) -> [String] {
        guard let data = ingredientString.data(using: .utf8) else { return [] }
        
        do {
            return try JSONDecoder().decode([String].self, from: data)
        } catch {
            print("Failed to parse string:", error)
            return []
        }
    }
    
    
    

    override func viewDidLoad() {
        super.viewDidLoad()
        RecipeNameLabel.text = selectedRecipe.title
        
        let allIngredientsArray = parseString(selectedRecipe.ingredients ?? "")
        let allIngredients = allIngredientsArray.map { "• \($0)" }.joined(separator: "\n")
        
        let allDirectionsArray = parseString(selectedRecipe.directions ?? "")
        let allDirections = allDirectionsArray.map { "• \($0)" }.joined(separator: "\n\n")

        
        text.text = ("Ingredients: \n\n\(allIngredients) \n\n\n\nDirections: \n\n\(allDirections)")
        // Do any additional setup after loading the view.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
