//
//  StreakViewController.swift
//  FeedTheFridge3
//
//  Created by Micha Glissmann on 13/04/2026.
//

import UIKit
//date is today (Monday 13th April)
//let publicToday = Date()

//date is tomorrow (Tuesday 14th April)
//let publicToday = Date.now.addingTimeInterval(86400)

//date is 4 days in the future (Friday 17th April)
let publicToday = Date.now.addingTimeInterval(86400 * 4)



class StreakViewController: UIViewController {
    
    
    @IBOutlet weak var sundayImg: UIImageView!
    @IBOutlet weak var mondayImg: UIImageView!
    @IBOutlet weak var tuesdayImg: UIImageView!
    @IBOutlet weak var wednesdayImg: UIImageView!
    @IBOutlet weak var thursdayImg: UIImageView!
    @IBOutlet weak var fridayImg: UIImageView!
    @IBOutlet weak var saturdayImg: UIImageView!
    @IBOutlet weak var whiteImg: UIImageView!
    
    
    @IBOutlet weak var currentLabel: UILabel!
    @IBOutlet weak var longestLabel: UILabel!
    
    
    let userDefaults = UserDefaults.standard
    
    let todayIndex = Calendar.current.component(.weekday, from: publicToday)
    
    
    //takes day of the week as an int (Sunday=1, Monday=2 etc.) and uses it as a key for userDefaults
    func checkDate(_ dayOfWeek: Int) -> Bool {
        return userDefaults.bool(forKey: "\(dayOfWeek)")
    }
    
    func getCurrentStreak() -> Int {
        return userDefaults.integer(forKey: "currentStreak")
    }
    
    func getLongestStreak() -> Int {
        return userDefaults.integer(forKey: "longestStreak")
    }
    
    func getLastActiveDay() -> Date {
        let string = userDefaults.string(forKey: "lastActiveDay") ?? "2000-01-01"
        return stringToDate(string)
    }
    
    //conversion functions from date to string and vice versa generated by chat-gpt
    func dateToString(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }
    
    func stringToDate(_ string: String) -> Date {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.date(from: string)!
    }
    
    
    
    

    override func viewDidLoad() {
        super.viewDidLoad()
        userDefaults.set(true, forKey: "\(todayIndex)")
        
        let calendar = Calendar.current
        
        
        
        var currentStreak = getCurrentStreak()
        let lastActiveDay = getLastActiveDay()
        var longestStreak = getLongestStreak()
        
        
        if calendar.isDate(lastActiveDay, inSameDayAs: calendar.date(byAdding: .day, value: -1, to: publicToday)!) {
            print("updating streak")
            currentStreak += 1
            userDefaults.set(currentStreak, forKey: "currentStreak")
        }
        else if !calendar.isDate(lastActiveDay, inSameDayAs: publicToday) {
            currentStreak = 1
            print("Create new streak")
            userDefaults.set(currentStreak, forKey: "currentStreak")
        }
        else {
            print("Logged in today!")
        }
        
        userDefaults.set(dateToString(publicToday), forKey: "lastActiveDay")
        
        if currentStreak > longestStreak {
            longestStreak.self = currentStreak
            userDefaults.set(longestStreak, forKey: "longestStreak")
        }
        
        
        
        
        longestLabel.text = "Longest Streak: \(longestStreak)"
        currentLabel.text = "Current Streak: \(currentStreak)"
        
        
        
        let firstDayOfWeek = 1
        
        sundayImg.image = checkDate(firstDayOfWeek) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        sundayImg.tintColor = checkDate(firstDayOfWeek) ? .systemOrange : .darkGray
        
        mondayImg.image = checkDate(firstDayOfWeek+1) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        mondayImg.tintColor = checkDate(firstDayOfWeek+1) ? .systemOrange : .darkGray
        
        tuesdayImg.image = checkDate(firstDayOfWeek+2) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        tuesdayImg.tintColor = checkDate(firstDayOfWeek+2) ? .systemOrange : .darkGray
        
        wednesdayImg.image = checkDate(firstDayOfWeek+3) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        wednesdayImg.tintColor = checkDate(firstDayOfWeek+3) ? .systemOrange : .darkGray
        
        thursdayImg.image = checkDate(firstDayOfWeek+4) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        thursdayImg.tintColor = checkDate(firstDayOfWeek+4) ? .systemOrange : .darkGray
        
        fridayImg.image = checkDate(firstDayOfWeek+5) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        fridayImg.tintColor = checkDate(firstDayOfWeek+5) ? .systemOrange : .darkGray
        
        saturdayImg.image = checkDate(firstDayOfWeek+6) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        saturdayImg.tintColor = checkDate(firstDayOfWeek+6) ? .systemOrange : .darkGray
        
        whiteImg.frame.origin.x = CGFloat(28 + 47 * (todayIndex - 1))
        

        // Do any additional setup after loading the view.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
