//
//  StreakViewController.swift
//  FeedTheFridge3
//
//  Created by Micha Glissmann on 13/04/2026.
//

import UIKit
// MARK: - Testing with date
//date is today (Monday 13th April)
//let publicToday = Date()

//date is tomorrow (Tuesday 14th April)
let publicToday = Date.now.addingTimeInterval(86400)

//date is 4 days in the future (Friday 17th April)
//let publicToday = Date.now.addingTimeInterval(86400 * 4)



class StreakViewController: UIViewController {
    // MARK: - Set up
    
    @IBOutlet weak var sundayImg: UIImageView!
    @IBOutlet weak var mondayImg: UIImageView!
    @IBOutlet weak var tuesdayImg: UIImageView!
    @IBOutlet weak var wednesdayImg: UIImageView!
    @IBOutlet weak var thursdayImg: UIImageView!
    @IBOutlet weak var fridayImg: UIImageView!
    @IBOutlet weak var saturdayImg: UIImageView!
    @IBOutlet weak var whiteImg: UIImageView!
    
    
    @IBOutlet weak var currentLabel: UILabel!
    @IBOutlet weak var longestLabel: UILabel!
    
    
    let userDefaults = UserDefaults.standard
    
    let todayIndex = Calendar.current.component(.weekday, from: publicToday)
    
    
    // MARK: - Helper functions
    //takes day of the week as an int (Sunday=1, Monday=2 etc.) and uses it as a key for userDefaults
    func checkDate(_ dayOfWeek: Int) -> Bool {
        return userDefaults.bool(forKey: "\(dayOfWeek)")
    }
    
    static func getCurrentStreak() -> Int {
        return UserDefaults.standard.integer(forKey: "currentStreak")
    }
    
    static func getLongestStreak() -> Int {
        return UserDefaults.standard.integer(forKey: "longestStreak")
    }
    
    static func getLastActiveDay() -> Date {
        let string = UserDefaults.standard.string(forKey: "lastActiveDay") ?? "2000-01-01"
        return stringToDate(string)
    }
    
    //conversion functions from date to string and vice versa generated by chat-gpt
    static func dateToString(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }
    
    static func stringToDate(_ string: String) -> Date {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.date(from: string)!
    }
    
    
    
    

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // MARK: - User Defaults
        userDefaults.set(true, forKey: "\(todayIndex)")
        
        let calendar = Calendar.current

        
        var currentStreak = StreakViewController.getCurrentStreak()
        let lastActiveDay = StreakViewController.getLastActiveDay()
        var longestStreak = StreakViewController.getLongestStreak()
        
        
        //updating streak
        if calendar.isDate(lastActiveDay, inSameDayAs: calendar.date(byAdding: .day, value: -1, to: publicToday)!) {
            currentStreak += 1
            userDefaults.set(currentStreak, forKey: "currentStreak")
        }
        // creating new streaks
        else if !calendar.isDate(lastActiveDay, inSameDayAs: publicToday) {
            currentStreak = 1
            userDefaults.set(currentStreak, forKey: "currentStreak")
        }

        
        userDefaults.set(StreakViewController.dateToString(publicToday), forKey: "lastActiveDay")
        
        if currentStreak > longestStreak {
            longestStreak.self = currentStreak
            userDefaults.set(longestStreak, forKey: "longestStreak")
        }
        
        
        
        
        // MARK: - Display streak
        longestLabel.text = "Longest Streak: \(longestStreak)"
        currentLabel.text = "Current Streak: \(currentStreak)"
        
        
        
        let firstDayOfWeek = 1
        
        sundayImg.image = checkDate(firstDayOfWeek) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        sundayImg.tintColor = checkDate(firstDayOfWeek) ? .systemOrange : .darkGray
        
        mondayImg.image = checkDate(firstDayOfWeek+1) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        mondayImg.tintColor = checkDate(firstDayOfWeek+1) ? .systemOrange : .darkGray
        
        tuesdayImg.image = checkDate(firstDayOfWeek+2) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        tuesdayImg.tintColor = checkDate(firstDayOfWeek+2) ? .systemOrange : .darkGray
        
        wednesdayImg.image = checkDate(firstDayOfWeek+3) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        wednesdayImg.tintColor = checkDate(firstDayOfWeek+3) ? .systemOrange : .darkGray
        
        thursdayImg.image = checkDate(firstDayOfWeek+4) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        thursdayImg.tintColor = checkDate(firstDayOfWeek+4) ? .systemOrange : .darkGray
        
        fridayImg.image = checkDate(firstDayOfWeek+5) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        fridayImg.tintColor = checkDate(firstDayOfWeek+5) ? .systemOrange : .darkGray
        
        saturdayImg.image = checkDate(firstDayOfWeek+6) ? UIImage(systemName: "flame.circle") : UIImage(systemName: "circle")
        saturdayImg.tintColor = checkDate(firstDayOfWeek+6) ? .systemOrange : .darkGray
        
        whiteImg.frame.origin.x = CGFloat(28 + 47 * (todayIndex - 1))
        

    }
    


}
